### PR TITLE
Page header (image)

### PR DESCRIPTION
**Pull request by YorgunKelebek**
Now that we even have a tag cloud, I think it's time we made this look a little more like a blog site with a header.

Tweaked scrollToItem call to avoid scrolling to first item on first page load, which also allowed me to address that annoying line of code.

### CODE REVIEW

**Comment by YorgunKelebek** [comment]
image

**Comment by goofballLogic** [comment]
Nice header image!

**Comment by goofballLogic** [comment]
Am I the frog?

**Comment by YorgunKelebek** [comment]
> Am I the frog?

You know it! Of course, I am the kelebek...

**Comment by YorgunKelebek** [comment]
> Note: -ms- for flex is only valid for IE10

OK, we're not supporting IE10 -

**Pull request merged**
